#ifndef VULKANRENDERER_GLOBAL_H
#define VULKANRENDERER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VULKANRENDERER_LIBRARY)
#define VULKANRENDERER_EXPORT Q_DECL_EXPORT
#else
#define VULKANRENDERER_EXPORT Q_DECL_IMPORT
#endif

#endif // VULKANRENDERER_GLOBAL_H
